name: 'Create Package Swift File'
description: 'This action contains steps creating the Package.swift file for the shared XCFramework'
inputs:
  binary_target_checksum:
    description: 'The computed checksum for the swift package binary target.'
    required: true
runs:
  using: "composite"
  steps:
    - name: Create Package.swift
      uses: DamianReeves/write-file-action@master
      with:
        path: Package.swift
        contents: |
          // swift-tools-version: 5.9
          // The swift-tools-version declares the minimum version of Swift required to build this package.

          import PackageDescription

          let package = Package(
            name: "GodToolsShared",
            platforms: [
              .iOS(.v16),
            ],
            products: [
                .library(name: "GodToolsShared", targets: ["GodToolsShared"])
            ],
            targets: [
                .binaryTarget(
                  name: "GodToolsShared",
                  url: "<link to the uploaded XCFramework ZIP file>",
                  checksum: "${{ inputs.binary_target_checksum }}")
            ]
          )
        write-mode: overwrite