name: Build Library

on:
  push:
    branches: [main]
    tags: ['v[0-9]+*']
  pull_request:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  ORG_GRADLE_PROJECT_releaseBuild: ${{ github.event_name == 'push' && contains(github.ref, 'refs/tags/') }}
  ORG_GRADLE_PROJECT_versionSuffix: ${{ (github.event_name == 'pull_request' && format('PR{0}', github.event.pull_request.number)) || '' }}

jobs:
  build:
    name: Build
    # run on mac so iOS compilation is executed as well
    runs-on: macos-11
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Cache Konan
        uses: actions/cache@v3
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan-${{ github.sha }}
          restore-keys: ${{ runner.os }}-konan-
      - name: Setup Java JDK
        uses: actions/setup-java@v3.6.0
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build -x check --scan

  check_metadata:
    name: Check Publication Metadata
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Cache Konan
        uses: actions/cache@v3
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan-${{ github.sha }}
          restore-keys: ${{ runner.os }}-konan-
      - name: Check Publication Metadata
        uses: gradle/gradle-build-action@v2
        with:
          arguments: generateMetadataFileForKotlinMultiplatformPublication --scan

  ktlint:
    name: Ktlint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Cache Konan
        uses: actions/cache@v3
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan-${{ github.sha }}
          restore-keys: ${{ runner.os }}-konan-
      - name: Ktlint
        uses: gradle/gradle-build-action@v2
        with:
          arguments: ktlintCheck --scan
      - name: Archive ktlint results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: ktlint-results
          path: "**/build/reports/ktlint/"

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Cache Konan
        uses: actions/cache@v3
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan-${{ github.sha }}
          restore-keys: ${{ runner.os }}-konan-
      - name: Lint
        uses: gradle/gradle-build-action@v2
        with:
          arguments: lint --scan

  android_tests:
    name: Android Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Cache Konan
        uses: actions/cache@v3
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan-${{ github.sha }}
          restore-keys: ${{ runner.os }}-konan-
      - name: Cache Maven
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ github.sha }}
          restore-keys: ${{ runner.os }}-maven-
      - name: Run Android Unit Tests
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test koverMergedReport --scan --no-build-cache
      - name: Codecov
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
      - name: Archive test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: android-unit-test-results
          path: "**/build/reports/tests/"
      - name: Archive kover results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: kover-results
          path: "**/build/reports/kover/"

  ios_tests:
    name: iOS Unit Tests
    runs-on: macos-11
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Cache Konan
        uses: actions/cache@v3
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan-${{ github.sha }}
          restore-keys: ${{ runner.os }}-konan-
      - name: Setup Java JDK
        uses: actions/setup-java@v3.6.0
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Run iOS Unit Tests
        uses: gradle/gradle-build-action@v2
        with:
          arguments: iosX64Test iosX64BackgroundTest --scan

  js_tests:
    name: JS Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Cache Konan
        uses: actions/cache@v3
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan-${{ github.sha }}
          restore-keys: ${{ runner.os }}-konan-
      - name: Run JS Unit Tests
        uses: gradle/gradle-build-action@v2
        with:
          arguments: jsTest --scan
      - name: Archive test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: js-unit-test-results
          path: "**/build/reports/tests/"

  lint_ios_podspec:
    name: Lint iOS Podspec
    runs-on: macos-11
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Cache Konan
        uses: actions/cache@v3
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan-${{ github.sha }}
          restore-keys: ${{ runner.os }}-konan-
      - name: Setup Java JDK
        uses: actions/setup-java@v3.6.0
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Install CocoaPods
        run: bundle install
      - name: Create podspec
        uses: gradle/gradle-build-action@v2
        with:
          arguments: podspec
      - name: Lint podspec
        run: pod spec lint *.podspec --allow-warnings

  deploy:
    name: Publish Library
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || contains(github.ref, 'refs/tags/'))
    needs: [ build, check_metadata, ktlint, lint, android_tests, ios_tests, js_tests ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Publish library
        uses: gradle/gradle-build-action@v2
        with:
          arguments: publish --scan
        env:
          ORG_GRADLE_PROJECT_cruGlobalMavenRepositoryUsername: ${{ secrets.JFROG_USERNAME }}
          ORG_GRADLE_PROJECT_cruGlobalMavenRepositoryPassword: ${{ secrets.JFROG_PASSWORD }}

  deploy_ios_podspec:
    name: Publish iOS Podspec
    runs-on: macos-11
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || contains(github.ref, 'refs/tags/'))
    needs: [ build, check_metadata, ktlint, lint, ios_tests ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Cache Konan
        uses: actions/cache@v3
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan-${{ github.sha }}
          restore-keys: ${{ runner.os }}-konan-
      - name: Setup Java JDK
        uses: actions/setup-java@v3.6.0
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Install CocoaPods
        run: bundle install
      - name: Create podspec
        uses: gradle/gradle-build-action@v2
        with:
          arguments: podspec
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - name: Add CruGlobal CocoaPods Repo
        run: pod repo add CruGlobal git@github.com:CruGlobal/cocoapods-specs.git
      - name: Push podspec
        run: pod repo push CruGlobal *.podspec --allow-warnings
