name: Build Library

on:
  push:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  cancel-previous:
    name: Cancel Stale In-progress Builds
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.0
        with:
          access_token: ${{ github.token }}

  deploy:
    name: Publish Library
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Cache Gradle
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Configure JFrog credentials
        env:
          JFROG_USERNAME: ${{ secrets.JFROG_USERNAME }}
          JFROG_PASSWORD: ${{ secrets.JFROG_PASSWORD }}
        run: |
          mkdir -p ~/.gradle
          echo cruGlobalMavenRepositoryUsername=$JFROG_USERNAME >> $HOME/.gradle/gradle.properties
          echo cruGlobalMavenRepositoryPassword=$JFROG_PASSWORD >> $HOME/.gradle/gradle.properties
      - name: Publish library
        run: ./gradlew publish --parallel

  ios_podspec:
    name: iOS Podspec
    runs-on: macos-latest
    if: github.event_name == 'push'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Cache Gradle
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Install CocoaPods
        run: bundle install
      - name: Create podspec
        run: ./gradlew podspec

      # Lint podspec if not a push to the main branch
      - name: Lint podspec
        if: github.ref != 'refs/heads/main'
        run: pod spec lint *.podspec --allow-warnings

      # Deploy podspec if push to main branch
      - name: Install SSH key
        if: github.ref == 'refs/heads/main'
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - name: Add CruGlobal CocoaPods Repo
        if: github.ref == 'refs/heads/main'
        run: pod repo add CruGlobal git@github.com:CruGlobal/cocoapods-specs.git
      - name: Push podspec
        if: github.ref == 'refs/heads/main'
        run: pod repo push CruGlobal *.podspec --allow-warnings
