name: "Validate Git LFS"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  validate-lfs-pointers:
    name: "Validate Git LFS pointers"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: git lfs fsck --pointers
