name: Trigger Release

on:
  push:
    branches: [publishWorkflow]
#  workflow_dispatch:

jobs:
  publish_release:
    name: Trigger Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Find Current Version
        id: vars
        run: |
          grep version gradle.properties >> $GITHUB_OUTPUT
#          RELEASE_VERSION=`grep version gradle.properties | sed 's/version=//'`
#          echo "::set-env name=RELEASE_VERSION::$RELEASE_VERSION
      - name: Create Tag
        run: |
          git tag v${{ steps.vars.outputs.version }}
          git tag
