name: Trigger Release

on:
  push:
    branches: [publishWorkflow]
#  workflow_dispatch:

jobs:
  publish_release:
    name: Trigger Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Find Current Version
        id: current_version
        run: grep version gradle.properties >> $GITHUB_OUTPUT
      - name: Create Tag
        env:
          TAG_NAME: tmp-v${{ steps.current_version.outputs.version }}
        run: |
          git tag $TAG_NAME
          git tag
#          git push origin tmp-v${{ steps.current_version.outputs.version }}
      - name: Bump Version
        id: bump_version
        uses: actions-ecosystem/action-bump-semver@v1
        with:
          current_version: ${{ steps.current_version.outputs.version }}
          level: patch
      - name: Update version for new development
        run: sed -i "s/version=${{ steps.current_version.outputs.version }}/version=${{ steps.bump_version.outputs.new_version }}/" gradle.properties
      - run: git diff
